apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  ROLLBACK_KEY: "{{ .Values.global.rollbackKey }}"
  # Passwords
  AUTH_DB_PASSWORD: "{{ .Values.postgresql.auth.password }}"
  USER_DB_PASSWORD: "{{ .Values.postgresql.user.password }}"
  ORDER_DB_PASSWORD: "{{ .Values.postgresql.order.password }}"
  MONGO_ROOT_PASSWORD: "{{ .Values.mongo.rootPassword }}"